### ISSUE TITLE
Sometimes doesn't add remote upload

### ISSUE THREAD

**Issue by krazyjakee** [Offcloud/offcloud-ext-chrome#2]
To recreate:

- Right click magnet link
- Hover over offcloud menu
- Click Remote upload
- Success message appears
- Go to offcloud
- Nothing has been added

**Comment by Offcloud** [comment]
This does not seem to be an issue related to the extension, but perhaps to the backend and/or your network configuration. Please kindly open a support ticket under your account. Our team will follow this up in private with you. Thanks.
